MODEL:
  META_ARCHITECTURE: "MaskFormer"
  # Swin Backbone pre-trained 가중치 경로 (3채널 pretrained → 4채널로 자동 init 됨)
  WEIGHTS: "pretrained/swin_base_patch4_window7_224_22k.pth"

  PIXEL_MEAN: [1.5530, 0.2541, 100814.0726, 19.2185]
  PIXEL_STD : [8.2976, 6.2316, 1461.2256, 15.8173]

  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    PRETRAIN_IMG_SIZE: 224
    PATCH_SIZE     : 8           # ← 16 또는 8
    IN_CHANS       : 4           # climate 변수 4개
    EMBED_DIM      : 96
    DEPTHS         : [2, 2, 6, 2]
    NUM_HEADS      : [3, 6, 12, 24]
    WINDOW_SIZE    : 7
    MLP_RATIO      : 4.0
    QKV_BIAS       : True
    QK_SCALE       : null
    DROP_RATE      : 0.0
    ATTN_DROP_RATE : 0.0
    DROP_PATH_RATE : 0.3
    APE            : False
    PATCH_NORM     : True
    OUT_FEATURES   : ["res2","res3","res4","res5"]

  SEM_SEG_HEAD:
    NAME        : "MaskFormerHead"
    IN_FEATURES : ["res2","res3","res4","res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES : 2
    CONVS_DIM   : 256
    MASK_DIM    : 256
    NORM        : "GN"

  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "res5"
    DEEP_SUPERVISION      : True
    NO_OBJECT_WEIGHT      : 0.1
    DICE_WEIGHT           : 1.0
    MASK_WEIGHT           : 20.0
    CE_POS_WEIGHT         : 10.0    # ← 10 또는 7

INPUT:
  DATASET_MAPPER_NAME: "netcdf_semantic"
  # FORMAT             : "RGB"
  MIN_SIZE_TRAIN     : (192,)
  MAX_SIZE_TRAIN     : 192
  MIN_SIZE_TEST      : 192
  MAX_SIZE_TEST      : 192
  SIZE_DIVISIBILITY  : 32
  CROP:
    ENABLED: False

DATASETS:
  TRAIN: ("climatenet_full_train_patches",)
  TEST : ("climatenet_full_test_patches",)

DATALOADER:
  NUM_WORKERS             : 4
  FILTER_EMPTY_ANNOTATIONS: True

SOLVER:
  IMS_PER_BATCH       : 8        # batch당 처리
  BASE_LR             : 0.00005
  MAX_ITER            : 100
  CHECKPOINT_PERIOD   : 50
  WARMUP_ITERS        : 50
  LR_SCHEDULER_NAME   : "WarmupPolyLR"
  OPTIMIZER           : "ADAMW"
  BACKBONE_MULTIPLIER : 0.1
  WEIGHT_DECAY        : 0.05
  WEIGHT_DECAY_EMBED  : 0.0
  WEIGHT_DECAY_NORM   : 0.0
  CLIP_GRADIENTS:
    ENABLED   : True
    CLIP_TYPE : "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE : 2.0

TEST:
  EVAL_PERIOD: 1
  AUG:
    ENABLED: False

OUTPUT_DIR: "/data0/aix23606/soyeon/MaskFormer/output/swin_p8_bs8_w10"
VERSION   : 2
